--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mysql-rc
  labels: 
    app: mysql-app
spec: 
  replicas: 3
  selector: 
    app: mysql-app
    deployment: v1
  template: 
    metadata: 
      labels: 
        app: mysql-app
        deployment: v1
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              value: mysql
          image: mysql
          name: mysql
          ports: 
            - 
              containerPort: 3306
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.2"    
