--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    app: mysql-app
  name: mysql
spec: 
  replicas: 3
  selector: 
    app: mysql-app
  template: 
    metadata: 
      labels: 
        app: mysql-app
    spec: 
      containers: 
        - 
          env: 
            - 
              name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                configMapKeyRef: 
                  key: mysql.root.password
                  name: mysql-config
            - 
              name: MYSQL_DATABASE
              valueFrom: 
                configMapKeyRef: 
                  key: mysql.database
                  name: mysql-config
            - 
              name: MYSQL_USER
              valueFrom: 
                configMapKeyRef: 
                  key: mysql.user
                  name: mysql-config
            - 
              name: MYSQL_PASSWORD
              valueFrom: 
                configMapKeyRef: 
                  key: mysql.user
                  name: mysql-config
            - 
              name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom: 
                configMapKeyRef: 
                  key: mysql.allow.empty.password
                  name: mysql-config
          image: mysql
          name: mysql
          ports: 
            - 
              containerPort: 3306

