apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.5
        ports:
        - containerPort: 80
  strategy: 
    type: RollingUpdate
      rollingUpdate: 
        maxUnavailable: 75%
        maxSurge: 30%
  rollbackTo: 
    revision: 0
