--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  name: elasticsearch-logging-v1
  namespace: kube-system
spec: 
  replicas: 2
  selector: 
    k8s-app: elasticsearch-logging
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: elasticsearch-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec: 
      containers: 
        - 
          image: "gcr.io/google_containers/elasticsearch:1.9"
          name: elasticsearch-logging
          ports: 
            - 
              containerPort: 9200
              name: db
              protocol: TCP
            - 
              containerPort: 9300
              name: transport
              protocol: TCP
          resources: 
            limits: 
              cpu: "0.1"
            requests: 
              cpu: "0.1"
          volumeMounts: 
            - 
              mountPath: /data
              name: es-persistent-storage
      volumes: 
        - 
          emptyDir: {}
          name: es-persistent-storage



