--- 
apiVersion: v1
kind: Pod
metadata: 
  name: fluentd-elasticsearch
spec: 
  containers: 
    - 
      env: 
        - 
          name: ELASTICSEARCH_HOST
          value: "10.2.15.2"
        - 
          name: ELASTICSEARCH_PORT
          value: "9200"
      image: "fabric8/fluentd-kubernetes:v1.9"
      name: fluentd-elasticsearch
      resources: 
        limits: 
          cpu: "0.1"
      securityContext: 
        privileged: true
      volumeMounts: 
        - 
          mountPath: /var/log
          name: varlog
        - 
          mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
  volumes: 
    - 
      hostPath: 
        path: /var/log
      name: varlog
    - 
      hostPath: 
        path: /var/lib/docker/containers
      name: varlibdockercontainers
