--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  name: kibana-logging-v1
  namespace: kube-system
spec: 
  replicas: 1
  selector: 
    k8s-app: kibana-logging
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: kibana-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec: 
      containers: 
        - 
          env: 
            - 
              name: ELASTICSEARCH_URL
              value: "http://10.2.15.2:9200"
          image: "gcr.io/google_containers/kibana:1.3"
          name: kibana-logging
          ports: 
            - 
              containerPort: 5601
              name: ui
              protocol: TCP
          resources: 
            limits: 
              cpu: "0.1"
            requests: 
              cpu: "0.1"
